export const tweetsData = [
  {
    handle: `@TrollBot66756542 💎`,
    profilePic: `images/troll.jpg`,
    likes: 27,
    retweets: 10,
    tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    isOwner: false,
    uuid: "4b161eee-c0f5-4545-9c4b-8562944223ee",
  },
  {
    handle: `@Elon ✅`,
    profilePic: `images/musk.png`,
    likes: 6500,
    retweets: 234,
    tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
    replies: [
      {
        handle: `@TomCruise ✅`,
        profilePic: `images/tcruise.png`,
        tweetText: `Yes! Sign me up! 😎🛩`,
        uuid: "14a18eb8-9e39-4b4f-accf-c4d427900ed8",
      },
      {
        handle: `@ChuckNorris ✅`,
        profilePic: `images/chucknorris.jpeg`,
        tweetText: `I went last year😴`,
        uuid: "5e38bae9-102e-4fb4-9593-0b1683342e11",
      },
    ],
    isLiked: false,
    isRetweeted: false,
    isOwner: false,
    uuid: "3c23454ee-c0f5-9g9g-9c4b-77835tgs2",
  },
  {
    handle: `@NoobCoder12`,
    profilePic: `images/flower.png`,
    likes: 10,
    retweets: 3,
    tweetText: `Are you a coder if you only know HTML?`,
    replies: [
      {
        handle: `@StackOverflower ☣️`,
        profilePic: `images/overflow.png`,
        tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
        uuid: "f7abc851-6d89-433f-a810-1cfdfb3702ae",
      },
      {
        handle: `@YummyCoder64`,
        profilePic: `images/love.png`,
        tweetText: `You are wonderful just as you are! ❤️`,
        uuid: "6b8b05c2-33e4-45e9-9838-f54c51409a6d",
      },
    ],
    isLiked: false,
    isRetweeted: false,
    isOwner: false,
    uuid: "8hy671sff-c0f5-4545-9c4b-1237gyys45",
  },
];
